### ISSUE TITLE
 你好，有具体的部署流程嘛，谢谢

### ISSUE THREAD

**Issue by wangkai147** [Retainv/cloud-disk-based-on-oss#1]
你好，有具体的部署流程嘛，谢谢

**Comment by Retainv** [comment]
有的，私信我邮箱发给你772392403@qq.com

**Comment by jinxiaobai0720** [comment]
你好，这个项目没有sql文件，我跑不起来，请问这个scheme和data文件从哪里下载呢，麻烦了

**Comment by Retainv** [comment]
感谢你的支持！
数据库文档和部署文档已经上传到附件，请查收！
如果觉得项目还可以，请在Guthub上前后端都点个小小的star噢，感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Retainv/cloud-disk-based-on-oss"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 中午11:26
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Retainv/cloud-disk-based-on-oss]  你好，有具体的部署流程嘛，谢谢 (Issue #1)





 
你好，这个项目没有sql文件，我跑不起来，请问这个scheme和data文件从哪里下载呢，麻烦了
